"""Changed field for Comment model

Revision ID: 90106f0f6413
Revises: 4c7cb97b0cd1
Create Date: 2023-08-29 15:14:47.546652

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90106f0f6413'
down_revision: Union[str, None] = '4c7cb97b0cd1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('commentary', sa.String(length=500), nullable=True))
    op.drop_column('comment', 'content')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('content', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_column('comment', 'commentary')
    # ### end Alembic commands ###
