"""Changed owner field to author field in Comment model

Revision ID: ddec6ee267b4
Revises: a942c98d393a
Create Date: 2023-08-29 15:31:24.637424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ddec6ee267b4'
down_revision: Union[str, None] = 'a942c98d393a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('author_id', sa.Integer(), nullable=True))
    op.drop_constraint('comment_owner_id_fkey', 'comment', type_='foreignkey')
    op.create_foreign_key(None, 'comment', 'user', ['author_id'], ['id'])
    op.drop_column('comment', 'owner_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.create_foreign_key('comment_owner_id_fkey', 'comment', 'user', ['owner_id'], ['id'])
    op.drop_column('comment', 'author_id')
    # ### end Alembic commands ###
