"""Added back_populates

Revision ID: 10f223e6cd8f
Revises: 7d1e1640ec43
Create Date: 2023-08-29 22:48:38.032205

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10f223e6cd8f'
down_revision: Union[str, None] = '7d1e1640ec43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
