"""Added back_populates to comment field to user

Revision ID: 120a6eff301f
Revises: 9b85ae0632c1
Create Date: 2023-08-30 10:19:21.978200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '120a6eff301f'
down_revision: Union[str, None] = '9b85ae0632c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
