"""Added back_populates to author field

Revision ID: 9b85ae0632c1
Revises: 10f223e6cd8f
Create Date: 2023-08-30 10:16:19.480255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b85ae0632c1'
down_revision: Union[str, None] = '10f223e6cd8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
